name: "Build latest - Debian Buster"
on:
  push:
    branches:
    - master
    paths:
    - 'src/root/**'
    - 'src/Dockerfile-buster'
    - '.github/workflows/debian-buster-latest.yml'
  schedule:
  - cron:  '30 1 1,15 * *'

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: run dockerfile linting
      uses: brpaz/hadolint-action@master
      with:
        dockerfile:  "src/Dockerfile-buster"

    - name: run build
      run: docker build -t "quay.io/sqlexception/gitlab-runner:buster-latest" -f src/Dockerfile-buster src/

    - name: run container structure tests
      uses: plexsystems/container-structure-test-action@v0.2.0
      with:
        image: "quay.io/sqlexception/gitlab-runner:buster-latest"
        config: container-structure-test.yml
   
    - uses: azure/docker-login@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        login-server: quay.io
        username: ${{ secrets.QUAY_IO_DOCKER_USERNAME }}
        password: ${{ secrets.QUAY_IO_DOCKER_PASSWORD }}
        
    - name: "publish image to quay.io/sqlexception/gitlab-runner:buster-latest"
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: docker push "quay.io/sqlexception/gitlab-runner:buster-latest"